INSERT INTO radius.dictionary (`Type`,`Attribute`,Value,Format,Vendor,RecommendedOP,RecommendedTable,RecommendedHelper,RecommendedTooltip) VALUES
	 ('integer','Huawei-Input-Burst-Size',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Input-Average-Rate',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Input-Peak-Rate',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Output-Burst-Size',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Output-Average-Rate',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Output-Peak-Rate',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-In-Kb-Before-T-Switch',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Out-Kb-Before-T-Switch',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-In-Pkt-Before-T-Switch',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Out-Pkt-Before-T-Switch',NULL,NULL,'huawei',NULL,NULL,NULL,NULL);
INSERT INTO radius.dictionary (`Type`,`Attribute`,Value,Format,Vendor,RecommendedOP,RecommendedTable,RecommendedHelper,RecommendedTooltip) VALUES
	 ('integer','Huawei-In-Kb-After-T-Switch',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Out-Kb-After-T-Switch',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-In-Pkt-After-T-Switch',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Out-Pkt-After-T-Switch',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Remanent-Volume',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Tariff-Switch-Interval',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-ISP-ID',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Max-Users-Per-Logic-Port',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Command',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Priority',NULL,NULL,'huawei',NULL,NULL,NULL,NULL);
INSERT INTO radius.dictionary (`Type`,`Attribute`,Value,Format,Vendor,RecommendedOP,RecommendedTable,RecommendedHelper,RecommendedTooltip) VALUES
	 ('integer','Huawei-Control-Identifier',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Result-Code',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Connect-ID',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-PortalURL',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-FTP-Directory',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Exec-Privilege',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-IP-Address',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-Qos-Profile-Name',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-SIP-Server',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-User-Password',NULL,NULL,'huawei',NULL,NULL,NULL,NULL);
INSERT INTO radius.dictionary (`Type`,`Attribute`,Value,Format,Vendor,RecommendedOP,RecommendedTable,RecommendedHelper,RecommendedTooltip) VALUES
	 ('string','Huawei-Command-Mode',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Renewal-Time',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Rebinding-Time',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-IGMP-Enable',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-Destnation-IP-Addr',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-Destnation-Volume',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Startup-Stamp',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-IPHost-Addr',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Up-Priority',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Down-Priority',NULL,NULL,'huawei',NULL,NULL,NULL,NULL);
INSERT INTO radius.dictionary (`Type`,`Attribute`,Value,Format,Vendor,RecommendedOP,RecommendedTable,RecommendedHelper,RecommendedTooltip) VALUES
	 ('string','Huawei-Tunnel-VPN-Instance',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-VT-Name',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-User-Date',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-User-Class',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-PPP-NCP-Type',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-VSI-Name',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('ipaddr','Huawei-Subnet-Mask',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('ipaddr','Huawei-Gateway-Address',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Lease-Time',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('ipaddr','Huawei-Primary-WINS',NULL,NULL,'huawei',NULL,NULL,NULL,NULL);
INSERT INTO radius.dictionary (`Type`,`Attribute`,Value,Format,Vendor,RecommendedOP,RecommendedTable,RecommendedHelper,RecommendedTooltip) VALUES
	 ('ipaddr','Huawei-Secondary-WINS',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Input-Peak-Burst-Size',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Output-Peak-Burst-Size',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Reduced-CIR',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Tunnel-Session-Limit',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-Zone-Name',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-Data-Filter',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-Access-Service',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Accounting-Level',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Portal-Mode',NULL,NULL,'huawei',NULL,NULL,NULL,NULL);
INSERT INTO radius.dictionary (`Type`,`Attribute`,Value,Format,Vendor,RecommendedOP,RecommendedTable,RecommendedHelper,RecommendedTooltip) VALUES
	 ('string','Huawei-DPI-Policy-Name',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('ipaddr','huawei-Policy-Route',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-Framed-Pool',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-L2TP-Terminate-Cause',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Multi-Account-Mode',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-Queue-Profile',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Layer4-Session-Limit',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-Multicast-Profile',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-VPN-Instance',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-Policy-Name',NULL,NULL,'huawei',NULL,NULL,NULL,NULL);
INSERT INTO radius.dictionary (`Type`,`Attribute`,Value,Format,Vendor,RecommendedOP,RecommendedTable,RecommendedHelper,RecommendedTooltip) VALUES
	 ('string','Huawei-Tunnel-Group-Name',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-Multicast-Source-Group',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('ipaddr','Huawei-Multicast-Receive-Group',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-User-Multicast-Type',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Reduced-PIR',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-LI-ID',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('ipaddr','Huawei-LI-Md-Address',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-LI-Md-Port',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-LI-Md-VpnInstance',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Service-Chg-Cmd',NULL,NULL,'huawei',NULL,NULL,NULL,NULL);
INSERT INTO radius.dictionary (`Type`,`Attribute`,Value,Format,Vendor,RecommendedOP,RecommendedTable,RecommendedHelper,RecommendedTooltip) VALUES
	 ('integer','Huawei-Acct-Packet-Type',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Call-Reference',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-PSTN-Port',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Voip-Service-Type',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Acct-Connection-Time',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Error-Reason',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Remain-Monney',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('ipaddr','Huawei-Org-GK-ipaddr',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('ipaddr','Huawei-Org-GW-ipaddr',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('ipaddr','Huawei-Dst-GK-ipaddr',NULL,NULL,'huawei',NULL,NULL,NULL,NULL);
INSERT INTO radius.dictionary (`Type`,`Attribute`,Value,Format,Vendor,RecommendedOP,RecommendedTable,RecommendedHelper,RecommendedTooltip) VALUES
	 ('ipaddr','Huawei-Dst-GW-ipaddr',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-Access-Num',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Remain-Time',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Codec-Type',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-Transfer-Num',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-New-User-Name',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-Transfer-Station-Id',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('ipaddr','Huawei-Primary-DNS',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('ipaddr','Huawei-Secondary-DNS',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-ONLY-Account-Type',NULL,NULL,'huawei',NULL,NULL,NULL,NULL);
INSERT INTO radius.dictionary (`Type`,`Attribute`,Value,Format,Vendor,RecommendedOP,RecommendedTable,RecommendedHelper,RecommendedTooltip) VALUES
	 ('string','Huawei-Domain-Name',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-ANCP-Profile',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-HTTP-Redirect-URL',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-Loopback-Address',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-QoS-Profile-Type',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Max-List-Num',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Acct-IPv6-Input-Octets',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Acct-IPv6-Output-Octets',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Acct-IPv6-Input-Packets',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Acct-IPv6-Output-Packets',NULL,NULL,'huawei',NULL,NULL,NULL,NULL);
INSERT INTO radius.dictionary (`Type`,`Attribute`,Value,Format,Vendor,RecommendedOP,RecommendedTable,RecommendedHelper,RecommendedTooltip) VALUES
	 ('integer','Huawei-Acct-IPv6-Input-Gigawords',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Acct-IPv6-Output-Gigawords',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-DHCPv6-Option37',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-DHCPv6-Option38',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-User-Mac',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('ipv6addr','Huawei-DNS-Server-IPv6-address',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-DHCPv4-Option121',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-DHCPv4-Option43',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-Framed-Pool-Group',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('ipv6addr','Huawei-Framed-IPv6-Address',NULL,NULL,'huawei',NULL,NULL,NULL,NULL);
INSERT INTO radius.dictionary (`Type`,`Attribute`,Value,Format,Vendor,RecommendedOP,RecommendedTable,RecommendedHelper,RecommendedTooltip) VALUES
	 ('integer','Huawei-Acct-Update-Address',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-NAT-Policy-Name',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('ipaddr','Huawei-NAT-Public-Address',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-NAT-Start-Port',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-NAT-End-Port',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-NAT-Port-Forwarding',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-NAT-Port-Range-Update',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-DS-Lite-Tunnel-Name',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string # manual says text?','Huawei-PCP-Server-Name',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Public-IP-Addr-State',NULL,NULL,'huawei',NULL,NULL,NULL,NULL);
INSERT INTO radius.dictionary (`Type`,`Attribute`,Value,Format,Vendor,RecommendedOP,RecommendedTable,RecommendedHelper,RecommendedTooltip) VALUES
	 ('integer','Huawei-Auth-Type',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-Acct-Terminate-Subcause',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-Down-QOS-Profile-Name',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Port-Mirror',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-Account-Info',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-Service-Info',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('octets','Huawei-DHCP-Option',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-AVpair',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-Delegated-IPv6-Prefix-Pool',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('octets','Huawei-IPv6-Prefix-Lease',NULL,NULL,'huawei',NULL,NULL,NULL,NULL);
INSERT INTO radius.dictionary (`Type`,`Attribute`,Value,Format,Vendor,RecommendedOP,RecommendedTable,RecommendedHelper,RecommendedTooltip) VALUES
	 ('octets','Huawei-IPv6-Address-Lease',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('ipv6prefix # manual says strin','Huawei-IPv6-Policy-Route',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-MNG-IPv6',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-Flow-Info',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Flow-Id',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('ipaddr','Huawei-DHCP-Server-IP',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-Application-Type',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('octets # integer??','Huawei-Indication-Flag',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('ipaddr','Huawei-Original_NAS-IP_Address',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('integer','Huawei-User-Priority',NULL,NULL,'huawei',NULL,NULL,NULL,NULL);
INSERT INTO radius.dictionary (`Type`,`Attribute`,Value,Format,Vendor,RecommendedOP,RecommendedTable,RecommendedHelper,RecommendedTooltip) VALUES
	 ('string','Huawei-ACS-Url',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-Provision-Code',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('octets','Huawei-Application-Scene',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('octets # ether??','Huawei-MS-Maximum-MAC-Study-Number',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-GGSN-Vendor',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-GGSN-Version',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-Ext-Specific',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-Web-URL',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-Version',NULL,NULL,'huawei',NULL,NULL,NULL,NULL),
	 ('string','Huawei-Product-ID',NULL,NULL,'huawei',NULL,NULL,NULL,NULL);

